### ISSUE TITLE
Possible protection is enabled. Press "Unprotect" and check datasheet

### ISSUE THREAD

**Issue by PhamMinhKha** [boseji/CH341-Store#2]
what do I do now?
I have GD25Q64C bios from mainboard biostar tb250.
![image](https://user-images.githubusercontent.com/12944689/61458167-14290f80-a994-11e9-99a3-2ce6034a8559.png)

**Comment by boseji** [comment]
Can't help you with that.
We have only created this repository for information purpose and not the maintainer for any tools provided.
