### ISSUE TITLE
Programmer software (Windows)

### ISSUE THREAD

**Issue by BigBox2020** [boseji/CH341-Store#6]
https://drive.google.com/file/d/0ByEQKtsOckWBUVBqajZOUGtLcnM/view

This version seems to be clean and does not contain anything extra
v1.13

it may work with your CH341A programmer or may not. but at the very least this is a clean-ish copy that i could find

https://www.youtube.com/watch?v=L0ChYNwunUE
------------------------------

there also appears to be flashrom for windows
https://www.win-raid.com/t796f16-Guide-Using-CH-A-based-programmer-to-flash-SPI-EEPROM-5.html#msg41915

more details and download link  https://vdhout.nl/tag/ch341a

**Comment by boseji** [comment]
Thanks for your contribution.
I would list your contribution on the documentation.
We would also need help in validation to ensure that all the software is Virus free.

**Comment by boseji** [comment]
Your contributions have been published. 
We request all contributor to please help us with Virus free check for the listed closed-source packages.

Thanks again.

**Comment by BigBox2020** [comment]
here is the virus total scan of the first file

https://www.virustotal.com/gui/file/0b6aba1bfa041ea3484cb4e6750427de468ece553a9461dba388fee16ad3669a/detection

virus can for the Flashrom_Windows

https://www.virustotal.com/gui/file/0eb1e5cde08fa44e015c5b56d01e330078a32b4efad4336513ee789f974b559c/detection


Hope it helps

**Comment by boseji** [comment]
Thanks a lot for your contributions.
I have published the changes to the document.
Its great help for the community.
Now folks an use the programmer version provided by yourself with ease and no worry.

Please let me know if you want to add the file directly to repository, for easy access.

Once we are through hope we can conclude this issue.
