### ISSUE TITLE
Add ch341a_parallelprog

### ISSUE THREAD

**Issue by DSchndr** [boseji/CH341-Store#9]
I have made a simple parallel interface eeprom dumper (writing could also be implemented) with parts lying around some time ago, might be useful for some people

Requires 1x ch341a and 2x MCP23017 (i2c)

https://github.com/DSchndr/ch341a_parallelprog

**Comment by boseji** [comment]
Congratulations,

Thanks for your contribution we would add the same to our Read me page.

**Comment by boseji** [comment]
Added your generous contribution to the repository.

Let us know if you would like add any further information.

**Comment by boseji** [comment]
We have added your contributions. Please let us know if you have any additional feedback by opening this issue again. Thank you.
